2024-06-25 09:21:48,038 - [INFO] - arithmetic_mean.py. <module>() line: 30 - Старт программы
2024-06-25 09:21:58,143 - [ERROR] - arithmetic_mean.py. get_input_data() line: 12 - Ошибка ввода данных
2024-06-25 09:22:10,110 - [INFO] - arithmetic_mean.py. arithmetic_mean() line: 19 - Вычислено среднее арифметическое
2024-06-25 09:22:10,110 - [INFO] - arithmetic_mean.py. <module>() line: 36 - Работа завершена
2024-06-25 09:23:27,493 - [INFO] - arithmetic_mean.py. <module>() line: 30 - Старт программы
2024-06-25 09:23:32,511 - [ERROR] - arithmetic_mean.py. get_input_data() line: 13 - Ошибка ввода данных
2024-06-25 09:23:39,846 - [INFO] - arithmetic_mean.py. get_input_data() line: 10 - Введена последовательность (1.0, 2.0, 3.0)
2024-06-25 09:23:39,846 - [INFO] - arithmetic_mean.py. arithmetic_mean() line: 19 - Вычислено среднее арифметическое
2024-06-25 09:23:39,847 - [INFO] - arithmetic_mean.py. <module>() line: 36 - Работа завершена
2024-06-25 09:24:36,647 - [INFO] - arithmetic_mean.py. <module>() line: 29 - Старт программы
